In [ ]:
""" Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1. """

In [1]:
import numpy as np

In [3]:
def vender_matrix(ivector,n,increasing=False):
    if increasing:
        omatrix=np.array([x**i for x in ivector for i in range(n)]).reshape(ivector.size,n)
    elif not increasing:
        omatrix=np.array([x**(n-1-i) for x in ivector for i in range(n)]).reshape(ivector.size,n)
    return omatrix


In [7]:
ivector= np.array([1,2,3,4,5])
no_col=4
omatrix_dec=vender_matrix(ivector,no_col,False)
imatrix_inc=vender_matrix(ivector,no_col,True)
print("The input vector: ",ivector,"\n")
print("Number of columns in output matrix should be: ",no_col,"\n")
print("Vander matrix in dec order of powers:\n",omatrix_dec,"\n")
print("Vander matrix in inc order of powers:\n",imatrix_inc,"\n")



The input vector:  [1 2 3 4 5] 

Number of columns in output matrix should be:  4 

Vander matrix in dec order of powers:
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]] 

Vander matrix in inc order of powers:
 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]] 



In [ ]:
""" Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3."""

In [25]:
#winodw (n)=3
def moving_average(a,n):
    re=np.cumsum(a,dtype=float)
    re[n:]=re[n:]-re[:-n]
    return ret[n-1:]/n
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_average(a,3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
